### ISSUE TITLE
Pomysły do dodania

### ISSUE THREAD

**Issue by ZEKKEQ** [PolanieOnLine/PolanieOnLine#4]
## 💡 Opisz pomysł

- [ ] Adventure Island - coś podobnego do istniejącej już wyspy (dostępna opcja tylko dla osób, które ukończyły 1 etap resetu)
- [x] Nowy minerał - platyna
- [ ] Nowy platynowy set (dostępna opcja tylko dla osób, które ukończyły 1 etap resetu (LUB bardzo niski drop - okolice 0.001% - 0.01%))
- [ ] Nowy NPC odpowiedzialny za nowy minerał oraz set?
- [ ] Nowy unikalny system ulepszeń TYLKO platynowego setu (dostępna opcja tylko dla osób, które ukończyły 1 etap resetu)
- [ ] Blokada 'dragon landa' dla osób, które odrodziły się (hmmm) drugi raz?
- [ ] Nowe mapy - expowiska (dostępna opcja tylko dla osób, które ukończyły 1 etap resetu)

**Comment by ZEKKEQ** [comment]
Mapa adventure island została ukończona i gotowa do dodania do gry.
Częściowo przygotowano grafiki dla planowanego nowego seta przedmiotów z platyny.

**Comment by PolanieOnLine** [comment]
test
